# Generated by Django 5.2 on 2025-05-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_commentreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hanekawa',
            unique_together=set(),
        ),
    ]
